using WordFinder;
//Ejemplo
var matrix = new List<string>
{
    "JKDFHEUROQWIEMNSLDKFJGHPEIWURMNCXBVJKQOWIEURMNZBCVJAKSDFHQWIEURM",
    "QWOEIURMNCBXVJKQOWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJ",
    "MNXZBVJKQOWIEURMNCBVJKASDFHQOWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEU",
    "HQWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNC",
    "MNXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEUR",
    "QWOEIURMNCXBVJKQOWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJ",
    "MNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNCXZBVJKQ",
    "KAQWOEIURMNCXBVJKQOWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXB",
    "URMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNCXZBVJ",
    "VJKQWOEIURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEUR",
    "IEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDF",
    "BVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCB",
    "URMNCXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWI",
    "DFHQWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURM",
    "EURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFH",
    "VJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBV",
    "RMNCXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIE",
    "FHQWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMN",
    "URMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFHQ",
    "JKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJ",
    "MNCXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEU",
    "HQWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNC",
    "RMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFHQW",
    "KQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJK",
    "NCXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEUR",
    "QWIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNCX",
    "MNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFHQWI",
    "QOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKA",
    "CXZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURM",
    "WIEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNCXZ",
    "NCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFHQWIE",
    "OWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKAS",
    "XZBVJKQOWIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMN",
    "IEURMNCXZBVJKQOWIEURMNCBVJKASDFHQWOEIURMNCXBVJKASDFHQWIEURMNCXZB",
    "CBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASDFHQWIEU",
    "WIEURMNCBVJKASDFHQWIEURMNCXZBVJKQOWIEURMNCBXVJKQOWIEURMNCBVJKASD",
    "FHZQDLGYNARTMLCYDMVOBXUWORQYTRLCYEEUWAIHWIVBQVBPBWGFBFLIBXGBBGKZ",
    "ELWVEVUJCEDHIYLSRFYKDSQWJBXYQWALQKAGNMWPPISNCCUSOHJBUEZDNCVXWVHJ",
    "ZNPXDHOCWZMWFIFXZICRSFKWGBZUJSIEMCAJPBNPIUNOPELLMKSUJFLCZPJZKWYL",
    "HUFFQMDYHUMDAHKIODBDDSYQQWLKIOUNOWQUCKHKKPGIMIJRGKWTOUQPXLVPPPKT",
    "FBILUXMPTTRYKTUYSZGEYOCIWBEPVQDRGXHVROSAKJONEICHKAKRNKHMDWRCRIWU",
    "VCKTMJKMEBYRMWVJTSBKGUIIPREXBDTUAKRSODLUMVWKSDBTQFJQOFOQTOGLFPYD",
    "MOUMKGYJIFCGVFABJBSZLMKDTIYHWOIYTJVVVXYONMUHVKGCJVRIYSWUPBAJCRBM",
    "HJIUWRACOLMXVDHDVTYGRHOLXVPWDZNEYVEOETCTNMAYJZABHMJNLNMDYQDIQPMF",
    "GTJHNNXDQHUXIHKHDLDHZVQEDRPMZQPYAGYNIUNBDLQWYTLUSDPADMBRWQVEKKZJ",
    "FYDUKAXTRMVFHJYLPYYZXVQFPASGMVYUAFXIJCJGPQFIWSETIVCSRGXYTNPEBRCM",
    "DPQRQKWYAQOJLKDLLCWHAJJHMDLONSWCLHKJWRQDEHGBNBGWTBBTIASPZTRHTAHR",
    "TTPSRDSSZNKRSAEKSADCVFVBQKLFCLIVWGLHXEGYEIYVRLFVSOEYACEFELNPSSER",
    "KFPPBTBMLHFYQPOKYVDSSLZPEGJQTGXSFYPCULTEPZRSVZJBPBAKNYUTWLUTYWNI",
    "KSTEPSGNAGNNNMYBTNJEDBFKJJAUYJRLUMVPUUOVVPXMKGMMCGXAFPLNYIHJGZKV",
    "REIXGPKSARTQFLMEBUFBNJZKVQZYZBXICBJSFVMQDFQVGHWZGXVRSCCMUUEPYATM",
    "OENSECMIEQIHTEMSCEZZDKQXKHUUEODNBZQVDCAPHSVNOIPJWOYKRHDCZXWVIUJQ",
    "FECGHCESRIQICJQOOKMKQRPYCJEZNHGFYWKYCQPWVBHALIBVRNOGKBETFIBYLRBB",
    "BIXRXMYYOGHHVNZHVTNAKXTMRNGDSCJNSDFPWWZZHOLEPGZCNIDCVVJKWIZYDREC",
    "JRALIJUTQHGUSSJTXFOGLRCHDGSJJOYOJTFAVBHLMPYRIYQMGFFDOZMVCVDQOGSH",
    "IUTJPTMNHSRFLRHQSJEUOQBKCHVJTKWMIQINIPGSIASCLDUGRAIYKNSVXDMVHADN",
    "DFKLKJJJXVMEALLGLVMMMDZXOUELWIOVJKEFNXFSOUIQAWXYLVRDNUCQPYJMHWHA",
    "NLPBBWECPUDLPOZFUKCTVTZWJTKRRLNZLSXMPCFSAYCLSQIBIVJYRXTXBYZRRVXL",
    "ODVOSRCYXULVTNBLNQCKAZFZXNQTFJCIFZRPZCTETYKAYBTLGZMTWIROISOWOCEM",
    "PQIWHQTOKVIQHGNLVGLBZCOEMSCZUWOOYKSEYPDGTOKGKPMGIBRSXUWKLZNNJALI",
    "ZVHYFLWPYQPKENIWYXZFRJSPUFEKKVEARZJDZTTGRLBLZPKFUFQSZFBYVFNMVLNJ",
    "GZBCYVOWKMJCCJROEOQQQAEEWXOHHATWWIEQIQZAZNAFDAZWVOOBIUIAAIZUXHSF",
    "GNGZAASRTIVWWLWORABZOGSZOMMEWHEGEMBZILFALJZHISFZRIRBFDNOKPMRBDLR",
    "CICSVKKKTOITFKFCATFAQQVAEKUQBHSCDYGQMXMLPOLDKLVNWEHOCIBLQQDPCGSN",
    "OTTXGNFJKRDYXSGPGEENXZENROFKFARCUFMDZLXSWCIMDEXIAZXOGVIGRZDYGKZK",
    "TTCUHAHZBIURAOKUJZNHSIGJHPSJUJRXRDHIMQBHJZSYHRKINBNYHIYOTMHRERVI"

};

var wordstream = new List<string>
{
    "EE", "the", "the", "TT", "MN", "EFOP", "ef", "OP", "KL", "cd"
};

WordFinder.WordFinder finder = new WordFinder.WordFinder(matrix);
IEnumerable<string> result = finder.Find(wordstream);

foreach (var word in result)
{
    Console.WriteLine(word + " " + finder.CountWord(word));
}